name: 'Use flippy script to package Armvirt as OpenWrt'
author: 'ophub'
description: 'Package Armvirt as OpenWrt. Support Amlogic S9xxx STB, vplus, beikeyun and l1pro, etc.'
inputs:
  mode:
    description: 'Choose script.'
    required: false
    # TODO 这里换个脚本指定会报没有权限?public_funcs?copy_supplement_files?
    default: 'flippy'

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/openwrt_${{ inputs.mode }}.sh
      shell: bash
      
branding:
  icon: 'terminal'
  color: 'gray-dark'
